[camera]
type = "pinhole"
hfov = 45

#position = [ -7.0, 5.0, 7.0 ]
#direction = [ 1.3, -0.7, -1.0 ]

position = [ 0.0, 0.0, 7.0 ]
lookat = [ 0.0, 0.0, 0.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 400
pixelheight = 300

[envmap]
type = "gradient"
low = [ 1.0, 1.0, 1.0 ]
high = [ 1.0, 1.0, 1.0 ]
direction = [ 1.0, 0.0, 1.0 ]

#[[slabs]] # Floor
#min = [ -1000.0, -1000.0, -1000.0 ]
#max = [ 1000.0, -1.5, 1000.0 ]

[[meshes]]
file = "dacunni/uvcube-ramp.obj"
[meshes.material]
    type = "diffuse"
#    diffuse = [ 0.8, 0.8, 0.8 ]
    diffuse = "grayramp"

