[[namedmaterials]]
name = "heromat"
type = "diffusespecular"
diffuse = "/Volumes/Extra/data/textures/cc0textures.com/Marble006_2K-JPG/Marble006_2K_Color.jpg"
#specular = 
normalmap = "/Volumes/Extra/data/textures/cc0textures.com/Marble006_2K-JPG/Marble006_2K_Normal.jpg"

#/Volumes/Extra/data/textures/cc0textures.com/Marble006_2K-JPG/Marble006_2K_Color.jpg
#/Volumes/Extra/data/textures/cc0textures.com/Marble006_2K-JPG/Marble006_2K_Displacement.jpg
#/Volumes/Extra/data/textures/cc0textures.com/Marble006_2K-JPG/Marble006_2K_Normal.jpg
#/Volumes/Extra/data/textures/cc0textures.com/Marble006_2K-JPG/Marble006_2K_Roughness.jpg

