[[namedmaterials]]
name = "heromat"
type = "diffusespecular"
#diffuse = "/Volumes/Extra/data/textures/cc0textures.com/Marble006_2K-JPG/Marble006_2K_Color.jpg"
diffuse = "/Volumes/Extra/data/textures/texturehaven.com/white_rough_plaster_1k_jpg/white_rough_plaster_diff_1k.jpg"
specular = "/Volumes/Extra/data/textures/texturehaven.com/white_rough_plaster_1k_jpg/white_rough_plaster_spec_1k.jpg"
specular_exponent = 1.0
normalmap = "/Volumes/Extra/data/textures/texturehaven.com/white_rough_plaster_1k_jpg/white_rough_plaster_nor_1k.jpg"

