[camera]
type = "pinhole"
hfov = 30

position = [ 0.0, 0.0, 10.0 ]
direction = [ 0.0, 0.0, -1.0 ]
lookat = [ 0.2, 0.3, 0.5 ]
up = [ 0.0, 1.0, 0.0 ]

[[disklights]]
position = [ 0.0, 2.0, 0.0 ]
direction = [ 0.0, 1.0, 0.0 ]
radius = 0.5
intensity = [ 1.0, 1.0, 1.0 ]

[[disklights]]
position = [ 2.0, 2.0, 2.0 ]
direction = [ 1.0, 1.0, 0.0 ]
radius = 2.2
intensity = [ 0.2, 0.2, 10.0 ]

[sensor]
pixelwidth = 200
pixelheight = 200

[[spheres]]
radius = 1.0
    [spheres.material]
    type = "diffuse"
    diffuse = [ 1.0, 1.0, 1.0 ]

[[slabs]]
min = [ -1000.0, -1000.0, -1000.0 ]
max = [ 1000.0, -1.0, 1000.0 ]
    [slabs.material]
    type = "diffuse"
    diffuse = [ 0.5, 0.5, 0.5 ]
