FROM centos_compilers:latest

# Install Google Test
RUN git clone -q https://github.com/google/googletest.git /googletest \
    && mkdir -p /googletest/build \
    && cd /googletest/build \
    && cmake3 .. && make -j && make install \
    && cd / && rm -rf /googletest

# Install Google Benchmark
RUN git clone -q https://github.com/google/benchmark.git /googlebenchmark \
    && mkdir -p /googlebenchmark/build \
    && cd /googlebenchmark/build \
    && cmake3 .. && make -j && make install \
    && cd / && rm -rf /googlebenchmark

# Update library search path
RUN echo /usr/local/lib >> /etc/ld.so.conf && ldconfig

