FROM centos:latest

# Install any needed packages specified in requirements.txt
RUN yum install -y epel-release
RUN yum install -y --enablerepo=epel \
    git \
    make cmake3 \
    python34-devel \
    gcc-c++

# Update library search path
RUN echo /usr/local/lib >> /etc/ld.so.conf && ldconfig

