FROM ubuntu_compilers:latest

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Setup build
RUN mkdir build && cd build && cmake -DBUILD_PYTHON_BINDINGS:BOOL=OFF ..

# Run build
#RUN cd build && make -j

# Make port 80 available to the world outside this container
EXPOSE 80

