[[include]]
source = "standard/materials/refract-water.toml"

[[include]]
source = "standard/scenes/suzanne-and-spheres.toml"

[[disklights]]
position = [ 3.0, 4.0, 3.0 ]
direction = [ 1.0, 0.0, 0.0 ]
radius = 1.1
intensity = [ 5.0, 3.0, 3.0 ]

# Behind the refractive model
[[disklights]]
position = [ 1.0, 2.0, -5.0 ]
direction = [ 0.0, 0.0, -1.0 ]
radius = 1.1
intensity = [ 3.0, 3.0, 5.0 ]

