[camera]
type = "pinhole"
hfov = 45

# front
position = [ 0.0, 2.0, 6.0 ]
direction = [ 0.0, -0.2, -1.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 400
pixelheight = 300

[[meshes]]
#file = "blender/monkey_simple_smooth.obj"
file = "blender/monkey2.obj"
    [meshes.material]
    type = "refractive"
    ior = 1.333
    [[meshes.transform]]
    translate = [ 0.0, 1.2, 0.0 ]

[[spheres]]
radius = 0.5
position = [ 2.0, 0.5, 0.0 ]
    [spheres.material]
    type = "diffuse"
    diffuse = [ 0.9, 0.9, 0.9 ]

[[spheres]]
radius = 0.5
position = [ -2.0, 0.5, 0.0 ]
    [spheres.material]
    type = "mirror"

[[disklights]]
position = [ 3.0, 4.0, 3.0 ]
direction = [ 1.0, 0.0, 0.0 ]
radius = 1.1
intensity = [ 5.0, 5.0, 5.0 ]
#intensity = [ 0.5, 0.5, 0.5 ]

# Behind the refractive model
[[disklights]]
position = [ 1.0, 2.0, -5.0 ]
direction = [ 0.0, 0.0, -1.0 ]
radius = 1.1
intensity = [ 5.0, 5.0, 5.0 ]
#intensity = [ 0.5, 0.5, 0.5 ]

# Floor
[[slabs]]
min = [ -2.5, -0.5, -1.5 ]
max = [ 2.5, -0.04, 1.5 ]
