[[include]]
source = "standard/materials/mirror.toml"

[[include]]
source = "standard/scenes/suzanne-and-spheres.toml"

[[disklights]]
position = [ 3.0, 4.0, 3.0 ]
direction = [ 1.0, 0.0, 0.0 ]
radius = 1.1
#intensity = [ 0.0, 3.0, 3.0 ]
intensity = [ 5.0, 5.0, 5.0 ]

#[[disklights]]
#position = [ -3.0, 4.0, 3.0 ]
#direction = [ 1.0, 0.0, 0.0 ]
#radius = 0.1
##intensity = [ 3.0, 0.0, 0.0 ]
#intensity = [ 5.0, 5.0, 5.0 ]

