[camera]
type = "pinhole"
#hfov = 60
#hfov = 45
hfov = 20

position = [ 8.0, 16.0, 16.0 ]
lookat = [ 0.0, 0.5, 0.0 ]
up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 1200
pixelheight = 800

[envmap]

#type = "gradient"
#low = [ 0.0, 0.0, 0.0 ]
#high = [ 1.0, 1.0, 1.0 ]
#direction = [ 5.0, 1.0, 0.0 ]

type = "latlon"
file = "polyhaven.com/adams_place_bridge_1k.hdr"
#file = "polyhaven.com/kloppenheim_02_1k.hdr"
#file = "polyhaven.com/spruit_sunrise_1k.hdr"

[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
    [meshes.material]
    type = "diffusespecular"
    diffuse = [ 0.5, 0.5, 0.5 ]
    specular = [ 0.5, 0.5, 0.5 ]
    specular_exponent = 10.0
    [[meshes.transform]]
    translate = [ -3.0, 0.0, 0.0 ]

[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
    [meshes.material]
    type = "diffusespecular"
    diffuse = [ 0.5, 0.5, 0.5 ]
    specular = [ 0.5, 0.5, 0.5 ]
    specular_exponent = 100.0
    [[meshes.transform]]
    translate = [ 0.0, 0.0, 0.0 ]

[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
    [meshes.material]
    type = "diffusespecular"
    diffuse = [ 0.5, 0.5, 0.5 ]
    specular = [ 0.5, 0.5, 0.5 ]
    specular_exponent = 1000.0
    [[meshes.transform]]
    translate = [ 3.0, 0.0, 0.0 ]

# Floor
[[slabs]]
min = [ -100.0, -0.5, -100.0 ]
max = [  100.0, -0.04, 100.0 ]

    [slabs.material]
    type = "diffuse"
    diffuse = [ 0.1, 0.1, 0.1 ]
#    type = "mirror"

