#!/usr/bin/python

import glob
import os
import subprocess

# TODO - command line params for paths and options
# TODO - command line param for dry run
# TODO - command line param for verbose

#scene_path = "../../scenes/toml"
scene_path = "../../scenes/quicklook"
job_base_path = "jobs"
base_cmd = "trace_scene"
#options = "-s 10 -d 3 -t 3 -p 0.1"
options = "-s 10 -d 3 -t 3"

dry_run = False
verbose = False

scene_path = os.path.abspath(scene_path)

# TODO - param for this
bin_path = os.path.abspath('.')

# Update paths
os.environ['PATH'] = bin_path + ":" + os.environ['PATH']

print("Scene Path = {}".format(scene_path))

scenes = glob.glob(scene_path + "/*")

def run_dir(run_id):
    return "{:06}".format(run_id)

def run_path(run_id):
    return "{}/{}".format(job_base_path, run_dir(run_id))

def make_new_run():
    # Determine ID for this run
    run_id = 0
    
    while os.path.exists(run_path(run_id)):
        run_id += 1
    
    if not dry_run:
        os.makedirs(run_path(run_id))

        latest_link_path = '{}/latest'.format(job_base_path)
        try:
            os.unlink(latest_link_path)
        except:
            pass
        os.symlink(run_dir(run_id), latest_link_path)
    
    print("Run ID = {}".format(run_id))

    return run_id

run_id = make_new_run()

init_cwd = os.getcwd()

job_id = 0
for scene in scenes:
    job_path = "{}/{:04}".format(run_path(run_id), job_id)
    print("Job ID = {} Path = {} Scene = {}".format(job_id, job_path, scene))

    if not dry_run:
        if not os.path.exists(job_path):
            os.makedirs(job_path)
        os.chdir(job_path)

    cmd = "{} {} {}".format(base_cmd, options, scene)
    print("Command = {}".format(cmd))

    # Execute command
    if not dry_run:
        cmd_output = subprocess.check_output(cmd, shell=True,
                                             stderr=subprocess.STDOUT)
        if verbose:
            print(cmd_output)

        with open("output.txt", "w") as output_file:
            output_file.write(cmd_output)
    
    os.chdir(init_cwd)
    
    job_id += 1


