[camera]
type = "pinhole"
hfov = 30
#hfov = 45
#hfov = 60
#hfov = 75

position = [ 0.3, -0.2, -1.0 ]
lookat = [ -0.2, -0.2, 1.0 ]
up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 1000
pixelheight = 800

[[meshes]]
file = "casual-effects.com/fireplace_room/fireplace_room.obj"
scaletocube = 3.0

#[[pointlights]]
#position = [ -0.5, 0.0, 0.0 ]
#intensity = [ 1.0, 1.0, 1.0 ]

[[disklights]]
position = [ -0.5, 0.6, 0.0 ]
direction = [ 0.0, 1.0, 0.0 ]
radius = 0.25
intensity = [ 4.0, 4.0, 4.0 ]

