[[include]]
source = "standard/materials/mirror-glossy.toml"

[[include]]
source = "standard/scenes/suzanne-and-spheres.toml"

[[pointlights]]
position = [ 5.0, 5.0, 2.0 ]
intensity = [ 10.0, 10.0, 10.0 ]
