[[include]]
source = "standard/materials/smooth-blue-plastic.toml"

[[include]]
source = "standard/scenes/suzanne-and-spheres.toml"

[[pointlights]]
position = [ 5.0, 5.0, 2.0 ]
intensity = [ 20.0, 20.0, 20.0 ]
