[[include]]
source = "standard/materials/diffuse-white.toml"

[[include]]
source = "standard/scenes/suzanne-and-spheres.toml"

[[pointlights]]
position = [ 5.0, 5.0, 2.0 ]
intensity = [ 2.5, 2.5, 10.0 ]

[[pointlights]]
position = [ -5.0, 5.0, 2.0 ]
intensity = [ 10.0, 2.5, 2.5 ]

