version: 2
jobs:
  build:
    docker:
      - image: dacunni/hobby:ubuntu_compilers
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: "Setup Build"
          command: mkdir build && cd build && cmake ..
      - run:
          name: "Build"
          command: cd build && make -j install
      - run:
          name: "Test"
          command: cd build && ctest
      - store_artifacts:
          path: build/app/trace_scene
      - run:
          name: "Render Test: Quick Look Scenes"
          command: |
            mkdir -p build/app/render_tests
            cd build/app
            export PATH=`pwd`:$PATH
            cd render_tests
            trace_all -v -s ../../../scenes/quicklook
      - store_artifacts:
          path: build/app/render_tests

