version: 2
jobs:
  build:
    docker:
      - image: dacunni/hobby:ubuntu_compilers_deps
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: ls -lrt
      - run: echo "Setting up build environment"
      - run: mkdir build && cd build && cmake -DBUILD_PYTHON_BINDINGS:BOOL=OFF ..
      - run: echo "Building"
      - run: cd build && make -j

