version: 2.1
jobs:
  build:
    docker:
      - image: dacunni/hobby:ubuntu_compilers
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: "Setup Build"
          command: mkdir build && cd build && cmake ..
      - run:
          name: "Build"
          command: cd build && make -j install
      - store_artifacts:
          path: /workspace/build/app/trace_scene
      - persist_to_workspace:
          root: .
          paths:
            - . # Specify files/folders to save in the workspace
  unittest:
    docker:
      - image: dacunni/hobby:ubuntu_compilers
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - attach_workspace:
          at: /workspace
      - run: ls -l /workspace
      - run:
          name: "Test"
          command: cd /workspace/build && ctest
  rendertest:
    docker:
      - image: dacunni/hobby:ubuntu_compilers
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - attach_workspace:
          at: /workspace
      - run: ls -l /workspace
      - run:
          name: "Render Test: Quick Look Scenes"
          command: |
            cd /workspace
            mkdir -p build/app/render_tests
            cd build/app
            export PATH=`pwd`:$PATH
            cd render_tests
            trace_all -v -s ../../../scenes/quicklook
      - store_artifacts:
          path: /workspace/build/app/render_tests
workflows:
  build-test:
    jobs:
      - build
      - unittest:
          requires:
            - build
      - rendertest:
          requires:
            - build

