version: 2
jobs:
  build:
    docker:
      - image: dacunni/hobby:ubuntu_compilers
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: ls -l
      - run:
          name: "Setup Build"
          command: mkdir build && cd build && cmake -DBUILD_PYTHON_BINDINGS:BOOL=OFF ..
      - run:
          name: "Build"
          command: cd build && make -j
      - run: ls -lR build
      - run:
          name: "Test"
          command: cd build && ctest
      - store_artifacts:
          path: build/app/trace_scene

