[camera]
type = "pinhole"
hfov = 45

position = [ 0.0, 0.0, 10.0 ]
direction = [ 0.0, 0.0, -1.0 ]
lookat = [ 0.2, 0.3, 0.5 ]
up = [ 0.0, 1.0, 0.0 ]

[envmap]
type = "latlon"
#file = "latlon_furnace_0_8.png"
file = "latlon_furnace_0_8_100x50.png"

[sensor]
pixelwidth = 200
pixelheight = 200

[[spheres]]
radius = 1.0
    [spheres.material]
    type = "diffuse"
    diffuse = [ 1.0, 1.0, 1.0 ]

