[camera]
type = "pinhole"
hfov = 45

position = [ 0.0, 1.0, 20.0 ]
direction = [ 0.0, 0.0, -1.0 ]
up = [ 0.0, 1.0, 0.0 ]

focus_distance = 20.0
focus_divergence = 0.01

[envmap]

type = "gradient"
low = [ 0.0, 0.0, 0.0 ]
high = [ 1.0, 1.0, 1.0 ]
direction = [ 0.3, 0.0, 1.0 ]

[sensor]
pixelwidth = 800
pixelheight = 400

[[meshes]]
file = "clara.io/star-wars-vader-tie-fighter.obj"
    [[meshes.transform]]
    rotate_axis = [ 0.0, 0.0, 1.0 ]
    rotate_angle = -0.2

# left front
[[meshes]]
file = "clara.io/star-wars-vader-tie-fighter.obj"
    [[meshes.transform]]
    rotate_axis = [ 0.0, 0.0, 1.0 ]
    rotate_angle = -0.2
    [[meshes.transform]]
    translate = [ -4.0, 0.0, 3.0 ]

# left above behind
[[meshes]]
file = "clara.io/star-wars-vader-tie-fighter.obj"
    [[meshes.transform]]
    rotate_axis = [ 0.0, 0.0, 1.0 ]
    rotate_angle = -0.2
    [[meshes.transform]]
    translate = [ -4.0, 5.0, -15.0 ]

# right front
[[meshes]]
file = "clara.io/star-wars-vader-tie-fighter.obj"
    [[meshes.transform]]
    rotate_axis = [ 0.0, 0.0, 1.0 ]
    rotate_angle = -0.2
    [[meshes.transform]]
    translate = [ 4.0, 0.0, 8.0 ]



