[camera]
type = "pinhole"
hfov = 60

position = [ 0.0, 1.0, 20.0 ]
direction = [ 0.0, 0.0, -1.0 ]
up = [ 0.0, 1.0, 0.0 ]

focus_distance = 20.0
focus_divergence = 0.025

[envmap]

type = "gradient"
low = [ 0.0, 0.0, 0.0 ]
high = [ 1.0, 1.0, 1.0 ]
direction = [ 1.0, 1.0, 1.0 ]

[sensor]
pixelwidth = 800
pixelheight = 400

# Far
[[spheres]]
radius = 1.0
position = [ -3.0, 1.0, -10.0 ]
    [spheres.material]
    type = "diffuse"
    diffuse = [ 0.5, 0.5, 1.0 ]
[[spheres]]
radius = 1.0
position = [ 3.0, 1.0, -10.0 ]
    [spheres.material]
    type = "diffusespecular"
    diffuse = [ 0.5, 0.5, 1.0 ]
    specular = [ 0.5, 0.5, 0.5 ]

# Center
[[spheres]]
radius = 1.0
position = [ -3.0, 1.0, 0.0 ]
    [spheres.material]
    type = "diffuse"
    diffuse = [ 1.0, 0.5, 0.5 ]
[[spheres]]
radius = 1.0
position = [ 3.0, 1.0, 0.0 ]
    [spheres.material]
    type = "diffusespecular"
    diffuse = [ 1.0, 0.5, 0.5 ]
    specular = [ 0.5, 0.5, 0.5 ]

# Near
[[spheres]]
radius = 1.0
position = [ -3.0, 1.0, +10.0 ]
    [spheres.material]
    type = "diffuse"
    diffuse = [ 0.5, 1.0, 0.5 ]
[[spheres]]
radius = 1.0
position = [ 3.0, 1.0, +10.0 ]
    [spheres.material]
    type = "diffusespecular"
    diffuse = [ 0.5, 1.0, 0.5 ]
    specular = [ 0.5, 0.5, 0.5 ]

# Floor
[[slabs]]
min = [ -100.0, -0.5, -100.0 ]
max = [ 100.0, 0.0, 100.0 ]
    [slabs.material]
    type = "diffusespecular"
    diffuse = [ 0.8, 0.8, 0.8 ]
    specular = [ 0.5, 0.5, 0.5 ]


