
[camera]
type = "pinhole"
hfov = 60

position = [ 30.0, 16.0, 30.0 ]
lookat = [ 5.0, 0.5, 5.0 ]
up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 1200
pixelheight = 800

[envmap]

type = "gradient"
low = [ 0.0, 0.0, 0.0 ]
high = [ 1.0, 1.0, 1.0 ]
direction = [ 1.0, 0.2, 0.0 ]

# Floor
[[slabs]]
min = [ -100.0, -0.5, -100.0 ]
max = [  100.0, -0.04, 100.0 ]

    [slabs.material]
    type = "diffuse"
    diffuse = [ 0.5, 0.5, 0.5 ]

[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 0.0, 0.5, 0.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 0.0, 0.5, 3.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 0.0, 0.5, 6.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 0.0, 0.5, 9.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 0.0, 0.5, 12.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 3.0, 0.5, 0.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 3.0, 0.5, 3.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 3.0, 0.5, 6.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 3.0, 0.5, 9.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 3.0, 0.5, 12.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 6.0, 0.5, 0.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 6.0, 0.5, 3.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 6.0, 0.5, 6.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 6.0, 0.5, 9.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 6.0, 0.5, 12.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 9.0, 0.5, 0.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 9.0, 0.5, 3.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 9.0, 0.5, 6.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 9.0, 0.5, 9.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 9.0, 0.5, 12.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 12.0, 0.5, 0.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 12.0, 0.5, 3.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 12.0, 0.5, 6.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 12.0, 0.5, 9.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"
[[meshes.transform]]
translate = [ 12.0, 0.5, 12.0 ]
[[meshes.transform]]
scale = [ 2.0, 2.0, 2.0 ]
