[camera]
type = "pinhole"
hfov = 10
#hfov = 60

#focus_distance = 7.75
#focus_divergence = 0.01

position = [ 1.0, 0.25, 1.0 ]
lookat = [ 0.0, 0.05, 0.0 ]
up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 800
pixelheight = 600

[envmap]
#type = "gradient"
#low = [ 0.0, 0.0, 0.0 ]
#high = [ 1.0, 1.0, 1.0 ]
#direction = [ -1.0, 0.0, -1.0 ]

type = "latlon"
#file = "polyhaven.com/sepulchral_chapel_rotunda_1k.hdr"
file = "polyhaven.com/artist_workshop_1k.hdr"

[[meshes]]
file = "polyhaven.com/Camera/Camera_01_1k.obj"
    #[meshes.material]
    #type = "diffuse"
    #diffuse = [ 1.0, 1.0, 1.0 ]
    #type = "mirror"
    #type = "refractive"
    #ior = 1.5
    #beer = [ 0.5, 2.0, 1.0 ]   # pink
    #beer = [ 2.0, 0.5, 0.5 ]   # teal


# Floor - included floor is thin and light shines through
[[slabs]]
min = [ -0.2, -0.05, -0.2 ]
max = [ 0.2, 0.0, 0.2 ]
    [slabs.material]
    type = "diffuse"
    diffuse = [ 0.2, 0.2, 0.2 ]

