[camera]
type = "pinhole"
hfov = 60

# Quarter front
position = [ -7.0, 0.0, 7.0 ]
direction = [ 1.0, 0.0, -1.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 160
pixelheight = 120

[envmap]
type = "cubemap"

xneg = "NissiBeach/negx.jpg"
xpos = "NissiBeach/posx.jpg"
yneg = "NissiBeach/negy.jpg"
ypos = "NissiBeach/posy.jpg"
zneg = "NissiBeach/negz.jpg"
zpos = "NissiBeach/posz.jpg"

[[meshes]]
file = "casual-effects.com/bmw/bmw.obj"
scaletocube = 3.0

[meshes.material]
type = "diffuse"
diffuse = [ 1.0, 1.0, 1.0 ]

[[spheres]]
radius = 0.5
position = [ -2.5, -1.0, 5.0 ]

[[slabs]]
min = [ -10.0, -3.0, -10.0 ]
max = [ 10.0, -1.5, 10.0 ]
