[camera]
type = "pinhole"
hfov = 45

# Quarter front
position = [ -7.0, 5.0, 7.0 ]
direction = [ 1.3, -0.7, -1.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 200
pixelheight = 150

[envmap]
type = "cubemap"

xneg = "NissiBeach/negx.jpg"
xpos = "NissiBeach/posx.jpg"
yneg = "NissiBeach/negy.jpg"
ypos = "NissiBeach/posy.jpg"
zneg = "NissiBeach/negz.jpg"
zpos = "NissiBeach/posz.jpg"

[[slabs]] # Floor
min = [ -1000.0, -1000.0, -1000.0 ]
max = [ 1000.0, -1.5, 1000.0 ]

[[slabs]]
min = [ -1.0, 0.5, -1.0 ]
max = [ 1.0, -1.5, 1.0 ]

[[slabs]]
min = [ 1.0, 0.5, 1.0 ]
max = [ 3.0, -1.5, 3.0 ]

[[slabs]]
min = [ 1.0, 2.5, -1.0 ]
max = [ 3.0, -1.5, 1.0 ]


