[camera]
type = "pinhole"
#hfov = 45
hfov = 60

# Front
#position = [ 0.0, 0.0, 13.0 ]
#direction = [ 0.0, 0.0, -1.0 ]
# Quarter front
position = [ 9.0, 0.0, 12.0 ]
direction = [ -1.0, 0.0, -1.0 ]
# Above
#position = [ 0.0, 13.2, 0.0 ]
#direction = [ 0.01, -1.0, 0.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 600
pixelheight = 300
#pixelwidth = 2000
#pixelheight = 1000

[envmap]
type = "gradient"
low = [ 0.0, 0.0, 0.0 ]
high = [ 1.0, 1.0, 1.0 ]

[[meshes]]
file = "casual-effects.com/sportsCar/sportsCar.obj"
scaletocube = 15.0

# Floor
[[slabs]]
min = [ -1000.0, -1000.0, -1000.0 ]
max = [ 1000.0, -1.78, 1000.0 ]
