[camera]
type = "pinhole"
hfov = 60

position = [ 9.0, 0.0, -12.0 ]
#direction = [ -1.1, 0.0, -1.0 ]
lookat = [ -2.0, 0.0, 0.0 ]
up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 400
pixelheight = 200
#pixelwidth = 600
#pixelheight = 300

[envmap]
type = "gradient"
low = [ 0.0, 0.0, 0.0 ]
#high = [ 0.8, 0.6, 0.6 ]
#low = [ 0.0, 0.0, 0.0 ]
high = [ 1.0, 1.0, 1.0 ]

#type = "cubemap"

#xneg = "HornstullsStrand2/negx.jpg"
#xpos = "HornstullsStrand2/posx.jpg"
#yneg = "HornstullsStrand2/negy.jpg"
#ypos = "HornstullsStrand2/posy.jpg"
#zneg = "HornstullsStrand2/negz.jpg"
#zpos = "HornstullsStrand2/posz.jpg"

#xneg = "SaintPetersBasilica/negx.jpg"
#xpos = "SaintPetersBasilica/posx.jpg"
#yneg = "SaintPetersBasilica/negy.jpg"
#ypos = "SaintPetersBasilica/posy.jpg"
#zneg = "SaintPetersBasilica/negz.jpg"
#zpos = "SaintPetersBasilica/posz.jpg"

#xneg = "ArstaBridge/negx.jpg"
#xpos = "ArstaBridge/posx.jpg"
#yneg = "ArstaBridge/negy.jpg"
#ypos = "ArstaBridge/posy.jpg"
#zneg = "ArstaBridge/negz.jpg"
#zpos = "ArstaBridge/posz.jpg"

[[meshes]]
file = "casual-effects.com/sportsCar/sportsCar.obj"
scaletocube = 15.0

[[slabs]]
min = [ -1000.0, -1000.0, -1000.0 ]
max = [ 1000.0, -1.78, 1000.0 ]
