[camera]
type = "pinhole"
#hfov = 45
hfov = 60

position = [ 0.0, 1.0, 3.0 ]
direction = [ 0.0, 0.0, -1.0 ]
up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 1000
pixelheight = 1000

[[meshes]]
#file = "casual-effects.com/cornell_box/CornellBox-Empty-CO.obj"
#file = "casual-effects.com/cornell_box/CornellBox-Empty-RG.obj"
#file = "casual-effects.com/cornell_box/CornellBox-Empty-Squashed.obj" # FIXME - handle missing normal indices
#file = "casual-effects.com/cornell_box/CornellBox-Empty-White.obj"
#file = "casual-effects.com/cornell_box/CornellBox-Glossy-Floor.obj"
#file = "casual-effects.com/cornell_box/CornellBox-Glossy.obj"
#file = "casual-effects.com/cornell_box/CornellBox-Mirror.obj"
file = "casual-effects.com/cornell_box/CornellBox-Original.obj"
#file = "casual-effects.com/cornell_box/CornellBox-Sphere.obj"
#file = "casual-effects.com/cornell_box/CornellBox-Water.obj"
#file = "casual-effects.com/cornell_box/water.obj"

# TEMP - remove when we have emissive meshes
#[[pointlights]]
#position = [ 0.0, 1.25, -0.5 ]
#intensity = [ 0.3, 0.3, 0.3 ]

[[disklights]]
#position = [ 0.0, 1.95, 0.0 ]  # default
position = [ 0.0, 1.55, 0.0 ]  # lower for some shorter boxes (Sphere, Water)
direction = [ 0.0, -1.0, 0.0 ]
radius = 0.3
#intensity = [ 0.5, 0.5, 0.5 ]
intensity = [ 2.0, 2.0, 2.0 ]

