[camera]
type = "pinhole"
#hfov = 45
hfov = 60

position = [ 0.0, 1.0, 3.0 ]
direction = [ 0.0, 0.0, -1.0 ]
up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 1000
pixelheight = 1000

[[meshes]]
file = "casual-effects.com/CornellBox/CornellBox-Empty-RG.obj"

[[meshes]]
file = "casual-effects.com/mitsuba/mitsuba-sphere.obj"

#    [[meshes.transform]]
#    rotate_axis = [ 1.0, 0.0, 0.0 ]
#    rotate_angle = 1.5708
#
    [[meshes.transform]]
    scale = [ 0.5, 0.5, 0.5 ]
#
#    [[meshes.transform]]
#    translate = [ -0.5, 0.0, 0.0 ]

# TEMP - remove when we have emissive meshes
[[pointlights]]
position = [ -0.5, 1.25, 0.5 ]
intensity = [ 0.3, 0.3, 0.3 ]

