[[include]]
source = "standard/materials/smooth-white-plastic.toml"

[camera]
type = "pinhole"
hfov = 45

# front
position = [ 0.0, 2.0, 6.0 ]
direction = [ 0.0, -0.2, -1.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 400
pixelheight = 300

[envmap]
#type = "gradient"
#low = [ 0.0, 0.0, 0.0 ]
#high = [ 1.0, 1.0, 1.0 ]
#direction = [ 1.0, 1.0, 1.0 ]

type = "latlon"
file = "polyhaven.com/adams_place_bridge_1k.hdr"

[[meshes]]
#file = "blender/monkey_simple_smooth.obj"
#file = "blender/monkey2.obj"
file = "blender/suzanne-smooth.obj"
    [meshes.material]
    include = "heromat"
    [[meshes.transform]]
    #translate = [ 0.0, 1.0, 0.0 ]
    translate = [ 0.0, 1.2, 0.0 ]

[[spheres]]
radius = 0.5
position = [ 2.0, 0.5, 0.0 ]

[[spheres]]
radius = 0.5
position = [ -2.0, 0.5, 0.0 ]
    [spheres.material]
    type = "mirror"

# Floor
[[slabs]]
min = [ -2.5, -0.5, -1.5 ]
max = [ 2.5, -0.04, 1.5 ]
