[camera]
type = "pinhole"
#hfov = 45
hfov = 60

position = [ 0.0, 2.0, 15.0 ]
direction = [ 0.0, -0.1, -1.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 600
pixelheight = 300
#pixelwidth = 2000
#pixelheight = 1500

[envmap]
type = "gradient"
low = [ 0.0, 0.0, 0.0 ]
high = [ 0.8, 0.8, 0.8 ]
#low = [ 0.0, 0.0, 0.0 ]
#high = [ 1.0, 1.0, 1.0 ]
#low = [ 0.0, 0.0, 0.1 ]
#high = [ 0.8, 0.3, 0.0 ]
direction = [ 1.0, 0.0, 0.0 ]
#direction = [ 0.0, -0.8, -1.0 ]

#type = "cubemap"

#xneg = "NissiBeach/negx.jpg"
#xpos = "NissiBeach/posx.jpg"
#yneg = "NissiBeach/negy.jpg"
#ypos = "NissiBeach/posy.jpg"
#zneg = "NissiBeach/negz.jpg"
#zpos = "NissiBeach/posz.jpg"

#xneg = "SaintPetersBasilica/negx.jpg"
#xpos = "SaintPetersBasilica/posx.jpg"
#yneg = "SaintPetersBasilica/negy.jpg"
#ypos = "SaintPetersBasilica/posy.jpg"
#zneg = "SaintPetersBasilica/negz.jpg"
#zpos = "SaintPetersBasilica/posz.jpg"

[[meshes]]
file = "casual-effects.com/bmw/bmw.obj"
#scaletocube = 3.0

    [[meshes.transform]]
    scale = [ 0.012, 0.012, 0.012 ]
    [[meshes.transform]]
    translate = [ -4.0, 0.0, 0.0 ]
    [[meshes.transform]]
    rotate_axis = [ 0.0, 1.0, 0.0 ]
    rotate_angle = 1.5708

[[meshes]]
file = "casual-effects.com/sportsCar/sportsCar.obj"
#scaletocube = 10.0

    [[meshes.transform]]
    scale = [ 2.0, 2.0, 2.0 ]
    [[meshes.transform]]
    translate = [ 4.0, 0.0, 3.0 ]

[[spheres]]
radius = 0.5
position = [ -2.5, 0.5, 8.0 ]

[[spheres]]
radius = 0.5
position = [ -4.0, 0.5, 8.0 ]

    [spheres.material]
    type = "mirror"

[[slabs]]
min = [ -1000.0, -1000.0, -1000.0 ]
max = [ 1000.0, 0.0, 1000.0 ]

