[camera]
type = "pinhole"
hfov = 45

# Quarter front
position = [ -7.0, 5.0, 7.0 ]
direction = [ 1.3, -0.7, -1.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 400
pixelheight = 300

[envmap]
type = "gradient"
low = [ 0.0, 0.0, 0.0 ]
high = [ 1.0, 1.0, 1.0 ]
direction = [ 1.0, 0.0, 1.0 ]

[[slabs]] # Floor
min = [ -5.0, -5.0, -5.0 ]
max = [ 5.0, -1.5, 5.0 ]

[[slabs]]
min = [ -1.0, 0.5, -1.0 ]
max = [ 1.0, -1.5, 1.0 ]

[slabs.material]
type = "diffuse"
diffuse = [ 0.8, 0.0, 0.0 ]

[[slabs]]
min = [ 1.0, 0.5, 1.2 ]
max = [ 3.0, -1.5, 3.2 ]

[slabs.material]
type = "diffusespecular"
diffuse = [ 0.5, 0.5, 1.0 ]
specular = [ 0.6, 0.6, 0.6 ]

[[slabs]]
min = [ 1.2, 2.5, -1.0 ]
max = [ 3.2, -1.5, 1.0 ]

[slabs.material]
type = "diffuse"
diffuse = [ 0.2, 0.8, 0.2 ]

