[camera]
type = "pinhole"
hfov = 45

# Quarter front
position = [ -7.0, 5.0, 7.0 ]
direction = [ 1.3, -0.7, -1.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 400
pixelheight = 300

[envmap]
type = "gradient"
low = [ 0.0, 0.0, 0.0 ]
high = [ 1.0, 1.0, 1.0 ]
direction = [ 1.0, 0.0, 1.0 ]

[[slabs]] # Floor
min = [ -1000.0, -1000.0, -1000.0 ]
max = [ 1000.0, -1.5, 1000.0 ]

[[slabs]]
min = [ -1.0, 0.5, -1.0 ]
max = [ 1.0, -1.5, 1.0 ]

[[slabs]]
min = [ 1.0, 0.5, 1.0 ]
max = [ 3.0, -1.5, 3.0 ]

[[slabs]]
min = [ 1.0, 2.5, -1.0 ]
max = [ 3.0, -1.5, 1.0 ]


