[camera]
type = "pinhole"
hfov = 15
#type = "ortho"
#hsize = 8

# front
#position = [ 0.0, 2.0, 6.0 ]
#direction = [ 0.0, -0.35, -1.0 ]
# side
#position = [ -6.0, 2.0, 0.0 ]
#direction = [ 1.0, -0.35, 0.0 ]
# side
#position = [ 6.0, 2.0, 0.0 ]
#direction = [ -1.0, -0.35, 0.0 ]
# quarter
position = [ 6.0, 2.0, 6.0 ]
direction = [ -1.0, -0.35, -1.0 ]
# back
#position = [ 0.0, 2.0, -6.0 ]
#direction = [ 0.0, -0.35, 1.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 800
pixelheight = 600

[envmap]
#type = "gradient"
low = [ 0.0, 0.0, 0.0 ]
high = [ 1.0, 1.0, 1.0 ]
direction = [ -1.0, 0.0, -1.0 ]

type = "latlon"
#file = "polyhaven.com/adams_place_bridge_1k.hdr"
file = "polyhaven.com/sepulchral_chapel_rotunda_1k.hdr"

[[meshes]]
file = "thingiverse/dachshund/Cleaned-Dachshund_t_manuallyFilled.stl"
scaletocube = 0.5
    [meshes.material]
    #type = "diffuse"
    #diffuse = [ 1.0, 1.0, 1.0 ]
    #type = "mirror"
    type = "refractive"
    ior = 1.5
    #beer = [ 0.5, 2.0, 1.0 ]   # pink
    beer = [ 2.0, 0.5, 0.5 ]   # teal


# Floor - included floor is thin and light shines through
[[slabs]]
min = [ -0.8, -0.8, -1.2 ]
max = [ 0.8, -0.58, 0.8 ]
    [slabs.material]
    type = "diffuse"
    diffuse = [ 0.2, 0.2, 0.2 ]

