[camera]
type = "pinhole"
hfov = 45

# Full
#position = [ 0.0, 0.0, 10.0 ]
#direction = [ 0.0, 0.0, -1.0 ]
# Zoom
position = [ 2.0, 2.0, 5.0 ]
direction = [ 0.0, 0.0, -1.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 800
pixelheight = 800

#[[spheres]]
#radius = 1.0

[[meshes]]
file = "models/hairball.obj"
scaletocube = 7.0

