[camera]
type = "pinhole"
hfov = 45

# Full
#position = [ 0.0, 0.0, 10.0 ]
#direction = [ 0.0, 0.0, -1.0 ]
# Zoom
position = [ 2.0, 2.0, 5.0 ]
direction = [ 0.0, 0.0, -1.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 800
pixelheight = 800

[envmap]
type = "gradient"
low = [ 0.0, 0.0, 0.0 ]
high = [ 1.0, 1.0, 1.0 ]
direction = [ 1.0, 0.0, 1.0 ]

[[meshes]]
file = "hairball.obj"
scaletocube = 7.0

