[[include]]
source = "materials/diffuse-white.toml"

[[include]]
source = "scenes/suzanne-and-spheres.toml"

[[pointlights]]
position = [ 5.0, 5.0, 2.0 ]
intensity = [ 3.0, 3.0, 4.0 ]

[[pointlights]]
position = [ -5.0, 5.0, 2.0 ]
intensity = [ 4.0, 3.0, 3.0 ]

