[[include]]
source = "scenes/suzanne-and-spheres.toml"

[[pointlights]]
position = [ 5.0, 5.0, 2.0 ]
intensity = [ 0.5, 0.5, 4.0 ]

[[pointlights]]
position = [ -5.0, 5.0, 2.0 ]
intensity = [ 4.0, 0.5, 0.5 ]

