[camera]
type = "pinhole"
hfov = 30
#type = "ortho"
#hsize = 8

#position = [ -4.0, 2.0, -4.0 ]
position = [ 0.0, 2.0, 5.0 ]
lookat = [ 0.0, 0.5, 1.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 400
pixelheight = 300

#[envmap]
#type = "gradient"
#low = [ 0.0, 0.0, 0.0 ]
##high = [ 0.8, 0.6, 0.6 ]
#high = [ 0.8, 0.8, 0.8 ]
#direction = [ 1.0, 1.0, 0.0 ]
#type = "latlon"
##file = "hdrihaven/street_lamp_1k.hdr"
#file = "hdrihaven/adams_place_bridge_1k.hdr"
##file = "hdrihaven/kloppenheim_02_1k.hdr"
##file = "hdrihaven/spruit_sunrise_1k.hdr"

[[disklights]]
position = [ 3.0, 4.0, 3.0 ]
direction = [ 1.0, 0.0, 0.0 ]
radius = 2.0
#intensity = [ 0.0, 3.0, 3.0 ]
#intensity = [ 0.5, 0.5, 0.5 ]
intensity = [ 1.0, 1.0, 1.0 ]
#intensity = [ 2.0, 2.0, 2.0 ]
#intensity = [ 8.0, 8.0, 8.0 ]
#intensity = [ 15.0, 15.0, 15.0 ]

[[meshes]]
file = "blendswap.com/jars/jars.obj"
    [[meshes.transform]]
    scale = [ 10.0, 10.0, 10.0 ]
    [[meshes.transform]]
    translate = [ 0.0, 0.1, 0.0 ]

[[spheres]]
radius = 0.2
position = [ 0.5, 0.2, 1.5 ]
    [spheres.material]
    type = "diffuse"
    diffuse = [ 0.8, 0.8, 0.8 ]
[[spheres]]
radius = 0.2
position = [ 0.0, 0.2, 1.5 ]
    [spheres.material]
    type = "mirror"
[[spheres]]
radius = 0.2
position = [ -0.5, 0.2, 1.5 ]
    [spheres.material]
    type = "refractive"
    ior = 1.5

[[slabs]]
min = [ -1000.0, -1000.0, -1000.0 ]
max = [ 1000.0, -0.0, 1000.0 ]

