[camera]
type = "pinhole"
hfov = 45

position = [ 0.0, 0.0, 3.0 ]
direction = [ 0.0, 0.0, -1.0 ]
up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 1000
pixelheight = 1000

[[meshes]]
file = "models/casual-effects.com/living_room/living_room.obj"
scaletocube = 10.0

