[camera]
type = "pinhole"
hfov = 20
#type = "ortho"
#hsize = 8

position = [ 0.0, 200.0, 300.0 ]
direction = [ 0.15, -0.45, -1.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 400
pixelheight = 600

[envmap]

type = "gradient"
low = [ 0.0, 0.0, 0.0 ]
#low = [ 1.0, 1.0, 1.0 ]
high = [ 1.0, 1.0, 1.0 ]
direction = [ 1, 0, 0 ]

#type = "cubemap"
#xneg = "SaintPetersBasilica/negx.jpg"
#xpos = "SaintPetersBasilica/posx.jpg"
#yneg = "SaintPetersBasilica/negy.jpg"
#ypos = "SaintPetersBasilica/posy.jpg"
#zneg = "SaintPetersBasilica/negz.jpg"
#zpos = "SaintPetersBasilica/posz.jpg"

[[meshes]]
file = "myminifactory.com/scantheworld/41-smk-mater-dolorosa-germain-pilon-louvre-hollowback.stl"
    [meshes.material]
    type = "diffuse"
    diffuse = [ 1.0, 1.0, 1.0 ]

# Floor - included floor is thin and light shines through
[[slabs]]
min = [ -1000.0, -1000.0, -1000.0 ]
max = [ 1000.0, -0.5, 1000.0 ]
    [slabs.material]
    type = "diffuse"
    diffuse = [ 0.5, 0.5, 0.5 ]

