[camera]
type = "pinhole"
hfov = 45
#type = "ortho"
#hsize = 20

position = [ 0.0, 0.0, 10.0 ]
direction = [ 0.0, 0.0, -1.0 ]
lookat = [ 0.2, 0.3, 0.5 ]
up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 400
pixelheight = 200

#[[spheres]]
#radius = 1.0

[[meshes]]
name = "monkey1"
file = "models/blender/monkey_simple_smooth.obj"

#[[meshes.transforms]]
#	translate = [ -3.4, 4.7, 5.2 ]
	
#	[[meshes.transforms]]
#	scale = [ 4.2, 4.2, 4.2 ]
	
#	[[meshes.transforms]]
#	rotation.angle = 0.24
#	rotation.axis = [ 1.3, 2.3, 0.2 ]

