[camera]
type = "pinhole"
hfov = 35

# front
position = [ 0.0, 2.0, 6.0 ]
direction = [ 0.0, -0.2, -1.0 ]
# side
#position = [ -6.0, 2.0, 0.0 ]
#direction = [ 1.0, -0.2, 0.0 ]
# side
#position = [ 6.0, 2.0, 0.0 ]
#direction = [ -1.0, -0.2, 0.0 ]
# quarter
#position = [ 6.0, 2.0, 6.0 ]
#direction = [ -1.0, -0.2, -1.0 ]
# back
#position = [ 0.0, 2.0, -6.0 ]
#direction = [ 0.0, -0.2, 1.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 400
pixelheight = 300

[[meshes]]
file = "models/casual-effects.com/mitsuba/mitsuba.obj"

