[camera]
type = "pinhole"
hfov = 30
#type = "ortho"
#hsize = 8

position = [ 63.0, 200.0, 250.0 ]
direction = [ 0.0, -0.65, -1.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 400
pixelheight = 450

[[pointlights]]
position = [ -150.0, 100.0, 150.0 ]
intensity = [ 20000.0, 20000.0, 20000.0 ]

[[meshes]]
file = "myminifactory.com/scantheworld/smk16-kas115-pieta-michelangelo.stl"
    [meshes.material]
    type = "diffuse"
    diffuse = [ 1.0, 1.0, 1.0 ]

    [[meshes.transform]]
    rotate_axis = [ 1.0, 0.0, 0.0 ]
    rotate_angle = 1.5708

# Floor - included floor is thin and light shines through
[[slabs]]
min = [ -1000.0, -1000.0, -1000.0 ]
max = [ 1000.0, -0.5, 1000.0 ]
    [slabs.material]
    type = "diffuse"
    diffuse = [ 0.5, 0.5, 0.5 ]

