[camera]
type = "pinhole"
hfov = 45
#type = "ortho"
#hsize = 8

position = [ 0.0, -0.4, 0.0 ]
#position = [ 0.0, -4.0, 0.0 ]
direction = [ 1.0, 0.0, -0.5 ]

#position = [ 0.0, -0.0, 0.0 ]
#direction = [ 0.5, -0.6, 1.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 400
pixelheight = 400

[[meshes]]
file = "casual-effects.com/san-miguel/san-miguel.obj"
#file = "casual-effects.com/san-miguel-2/san-miguel.obj"
scaletocube = 10.0

