[camera]
type = "pinhole"
hfov = 45
#type = "ortho"
#hsize = 8

position = [ 0.0, -0.4, 0.0 ]
#position = [ 0.0, -4.0, 0.0 ]
direction = [ 1.0, 0.0, -0.5 ]

#position = [ -40.0, 0.0, 0.0 ]
#direction = [ 1.0, 0.0, 0.0 ]

#position = [ 0.0, -0.0, 0.0 ]
#direction = [ 0.5, -0.6, 1.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
#pixelwidth = 200
#pixelheight = 200
pixelwidth = 1000
pixelheight = 1000

[[meshes]]
file = "models/san-miguel/san-miguel.obj"
scaletocube = 10.0

[envmap]
#type = "gradient"
#low = [ 0.0, 0.0, 0.0 ]
#high = [ 0.8, 0.6, 0.6 ]
#low = [ 0.0, 0.0, 0.0 ]
#high = [ 1.0, 1.0, 1.0 ]

type = "cubemap"

xneg = "envmaps/NissiBeach/negx.jpg"
xpos = "envmaps/NissiBeach/posx.jpg"
yneg = "envmaps/NissiBeach/negy.jpg"
ypos = "envmaps/NissiBeach/posy.jpg"
zneg = "envmaps/NissiBeach/negz.jpg"
zpos = "envmaps/NissiBeach/posz.jpg"

#xneg = "envmaps/SaintPetersBasilica/negx.jpg"
#xpos = "envmaps/SaintPetersBasilica/posx.jpg"
#yneg = "envmaps/SaintPetersBasilica/negy.jpg"
#ypos = "envmaps/SaintPetersBasilica/posy.jpg"
#zneg = "envmaps/SaintPetersBasilica/negz.jpg"
#zpos = "envmaps/SaintPetersBasilica/posz.jpg"
