[camera]
type = "pinhole"
hfov = 45
#type = "ortho"
#hsize = 8

# plants along railing
#position = [ 0.0, -0.4, 0.0 ]
##position = [ 0.0, -4.0, 0.0 ]
#direction = [ 1.0, 0.0, -0.5 ]

#position = [ -40.0, 0.0, 0.0 ]
#direction = [ 1.0, 0.0, 0.0 ]

# fountain and tables through trees
position = [ 0.0, -0.0, 0.0 ]
direction = [ 0.5, -0.6, 1.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
#pixelwidth = 200
#pixelheight = 200
pixelwidth = 1000
pixelheight = 1000

[[meshes]]
file = "san-miguel/san-miguel.obj"
scaletocube = 10.0

[envmap]
type = "gradient"
low = [ 0.0, 0.0, 0.0 ]
high = [ 1.0, 1.0, 1.0 ]

#type = "latlon"
#file = "hdrihaven/adams_place_bridge_1k.hdr"

#type = "cubemap"
#
#xneg = "NissiBeach/negx.jpg"
#xpos = "NissiBeach/posx.jpg"
#yneg = "NissiBeach/negy.jpg"
#ypos = "NissiBeach/posy.jpg"
#zneg = "NissiBeach/negz.jpg"
#zpos = "NissiBeach/posz.jpg"

#xneg = "SaintPetersBasilica/negx.jpg"
#xpos = "SaintPetersBasilica/posx.jpg"
#yneg = "SaintPetersBasilica/negy.jpg"
#ypos = "SaintPetersBasilica/posy.jpg"
#zneg = "SaintPetersBasilica/negz.jpg"
#zpos = "SaintPetersBasilica/posz.jpg"
