[camera]
type = "pinhole"
hfov = 60
#type = "ortho"
#hsize = 20

position = [ 0.0, 0.0, 10.0 ]
direction = [ 0.0, 0.0, -1.0 ]
lookat = [ 0.2, 0.3, 0.5 ]
up = [ 0.0, 1.0, 0.0 ]

[envmap]

type = "gradient"
low = [ 1.0, 1.0, 1.0 ]
high = [ 1.0, 1.0, 1.0 ]

[sensor]
pixelwidth = 400
pixelheight = 200

[[spheres]]
radius = 1.0

[[spheres]]
radius = 1.0
position = [ 2.0, 0.0, 0.0 ]

[[spheres]]
radius = 0.5
position = [ -1.5, 0.0, 0.0 ]

[[spheres]]
radius = 0.5
position = [ -1.5, 0.0, 6.0 ]

[[spheres]]
radius = 10.0
position = [ 0.0, -11.0, 0.0 ]

