[camera]
type = "pinhole"
hfov = 60
#type = "ortho"
#hsize = 20

position = [ 0.0, 5.0, 10.0 ]
lookat = [ 0.2, 0.3, 0.5 ]
up = [ 0.0, 1.0, 0.0 ]

#[envmap]
#type = "gradient"
#low = [ 0.0, 0.0, 0.0 ]
#high = [ 0.2, 0.2, 0.2 ]
#direction = [ 1.0, 0.0, 0.0 ]

[sensor]
pixelwidth = 400
pixelheight = 200

[[spheres]]
radius = 1.0
    [spheres.material]
    type = "diffuse"
    diffuse = [ 0.9, 0.9, 0.9 ]

[[spheres]]
radius = 1.0
position = [ 2.0, 0.0, 0.0 ]
    [spheres.material]
    type = "diffuse"
    diffuse = [ 0.9, 0.9, 0.9 ]

[[spheres]]
radius = 0.5
position = [ -2.5, 0.0, 0.0 ]
    [spheres.material]
    type = "diffuse"
    diffuse = [ 0.9, 0.9, 0.9 ]

[[spheres]]
radius = 0.5
position = [ -1.5, 0.0, -3.0 ]
    [spheres.material]
    type = "emissive"
    emissive = [ 5.0, 0.0, 0.0 ]

[[spheres]]
radius = 0.5
position = [ 1.5, 1.0, 3.0 ]
    [spheres.material]
    type = "emissive"
    emissive = [ 0.0, 0.0, 5.0 ]

[[slabs]] # Floor
min = [ -1000.0, -1000.0, -1000.0 ]
max = [ 1000.0, -1.5, 1000.0 ]
