[camera]
type = "pinhole"
hfov = 10

position = [ 9.0, 0.0, 12.0 ]
direction = [ -1.1, 0.0, -1.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 600
pixelheight = 300

[[meshes]]
file = "models/casual-effects.com/sportsCar/sportsCar.obj"
scaletocube = 15.0

[[slabs]]
min = [ -1000.0, -1000.0, -1000.0 ]
max = [ 1000.0, -1.78, 1000.0 ]
