[camera]
type = "pinhole"
#hfov = 45
hfov = 60

# Front
#position = [ 0.0, 0.0, 13.0 ]
#direction = [ 0.0, 0.0, -1.0 ]
# Quarter front
position = [ 9.0, 0.0, 12.0 ]
direction = [ -1.0, 0.0, -1.0 ]
# Above
#position = [ 0.0, 13.2, 0.0 ]
#direction = [ 0.01, -1.0, 0.0 ]

up = [ 0.0, 1.0, 0.0 ]

[sensor]
#pixelwidth = 200
#pixelheight = 100
#pixelwidth = 400
#pixelheight = 200
#pixelwidth = 600
#pixelheight = 300
pixelwidth = 2000
pixelheight = 1000

[envmap]
#type = "gradient"
#low = [ 0.0, 0.0, 0.0 ]
#high = [ 0.8, 0.6, 0.6 ]
#low = [ 0.0, 0.0, 0.0 ]
#high = [ 1.0, 1.0, 1.0 ]

type = "cubemap"

#xneg = "envmaps/HornstullsStrand2/negx.jpg"
#xpos = "envmaps/HornstullsStrand2/posx.jpg"
#yneg = "envmaps/HornstullsStrand2/negy.jpg"
#ypos = "envmaps/HornstullsStrand2/posy.jpg"
#zneg = "envmaps/HornstullsStrand2/negz.jpg"
#zpos = "envmaps/HornstullsStrand2/posz.jpg"

#xneg = "envmaps/SaintPetersBasilica/negx.jpg"
#xpos = "envmaps/SaintPetersBasilica/posx.jpg"
#yneg = "envmaps/SaintPetersBasilica/negy.jpg"
#ypos = "envmaps/SaintPetersBasilica/posy.jpg"
#zneg = "envmaps/SaintPetersBasilica/negz.jpg"
#zpos = "envmaps/SaintPetersBasilica/posz.jpg"

#xneg = "envmaps/ArstaBridge/negx.jpg"
#xpos = "envmaps/ArstaBridge/posx.jpg"
#yneg = "envmaps/ArstaBridge/negy.jpg"
#ypos = "envmaps/ArstaBridge/posy.jpg"
#zneg = "envmaps/ArstaBridge/negz.jpg"
#zpos = "envmaps/ArstaBridge/posz.jpg"

xneg = "envmaps/NissiBeach/negx.jpg"
xpos = "envmaps/NissiBeach/posx.jpg"
yneg = "envmaps/NissiBeach/negy.jpg"
ypos = "envmaps/NissiBeach/posy.jpg"
zneg = "envmaps/NissiBeach/negz.jpg"
zpos = "envmaps/NissiBeach/posz.jpg"

[[meshes]]
file = "models/casual-effects.com/sportsCar/sportsCar.obj"
scaletocube = 15.0

# Floor
[[slabs]]
min = [ -1000.0, -1000.0, -1000.0 ]
max = [ 1000.0, -1.78, 1000.0 ]
