[camera]
type = "pinhole"
up = [ 0.0, 1.0, 0.0 ]
hfov = 90

position = [ 2.3, 4.6, 1.0 ]
direction = [ 0.0, 0.0, -1.0 ]
#lookat = [ 0.2, 0.3, 0.5 ]

[sensor]
pixelwidth = 512
pixelheight = 512

[[meshes]]
name = "monkey1"
file = "blender/monkey_simple_smooth.obj"

	[[meshes.transforms]]
	translate = [ -3.4, 4.7, 5.2 ]
	
	[[meshes.transforms]]
	scale = [ 4.2, 4.2, 4.2 ]
	
	[[meshes.transforms]]
	rotation.angle = 0.24
	rotation.axis = [ 1.3, 2.3, 0.2 ]

[[meshes]]
name = "sphere_mesh_1"
file = "blender/sphere.obj"

[[spheres]]
radius = 3.2

[[slabs]]
min = [ 3.2, 4.2, 5.1 ]
max = [ 5.6, 7.6, 9.1 ]

