[camera]
type = "pinhole"
hfov = 45
#type = "ortho"
#hsize = 8

position = [ 0.0, 1.0, 5.0 ]
lookat = [ 0.0, 0.0, 0.0 ]
up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 600
pixelheight = 400

[[disklights]]
position = [ 0.0, 1.5, 0.0 ]
direction = [ 0.0, 0.0, 1.0 ]
radius = 0.5
intensity = [ 0.9, 0.9, 0.9 ]

[[spheres]]
radius = 0.3
position = [ 0.0, 0.3, 2.0 ]
    [spheres.material]
    type = "refractive"
    ior = 1.5

[[slabs]]
min = [ -1000.0, -1000.0, -1000.0 ]
max = [ 1000.0, 0.0, 1000.0 ]
    [slabs.material]
    type = "diffuse"
    diffuse = [ 0.5, 0.5, 0.5 ]

