[camera]
type = "pinhole"
hfov = 45
#type = "ortho"
#hsize = 8

position = [ 0.0, 1.0, 5.0 ]
lookat = [ 0.0, 0.5, 0.0 ]
up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 600
pixelheight = 400

[[disklights]]
position = [ 1.5, 0.5, 0.0 ]
direction = [ 1.0, 0.0, 0.0 ]
radius = 0.25
#intensity = [ 0.9, 0.9, 0.9 ]
intensity = [ 10.0, 10.0, 10.0 ]

[[spheres]]
radius = 0.5
position = [ 0.0, 0.5, 0.0 ]
    [spheres.material]
    type = "refractive"
    ior = 1.5
    beer = [ 0.0, 2.0, 2.0 ]

# wall
[[slabs]]
min = [ -1.2, 1.0, -1.0 ]
max = [ -1.0, 0.0,  1.0 ]
    [slabs.material]
    type = "diffuse"
    diffuse = [ 0.5, 0.5, 0.5 ]

# floor
[[slabs]]
min = [ -1000.0, -1000.0, -1000.0 ]
max = [ 1000.0, 0.0, 1000.0 ]
    [slabs.material]
    type = "diffuse"
    diffuse = [ 0.5, 0.5, 0.5 ]

