[camera]
type = "pinhole"
hfov = 30

position = [ 0.0, 1.0, 5.0 ]
lookat = [ 0.0, 0.3, 2.0 ]
up = [ 0.0, 1.0, 0.0 ]

[sensor]
pixelwidth = 600
pixelheight = 400

[envmap]
type = "latlon"
file = "hdrihaven/adams_place_bridge_1k.hdr"

[[spheres]]
radius = 0.3
position = [ 0.0, 0.3, 2.0 ]
    [spheres.material]
    type = "refractive"
    ior = 1.5

[[spheres]]
radius = 0.1
position = [ -0.6, 0.1, 2.0 ]
    [spheres.material]
    type = "mirror"

[[spheres]]
radius = 0.1
position = [ 0.6, 0.1, 2.0 ]
    [spheres.material]
    type = "diffuse"
    diffuse = [ 0.5, 0.5, 0.5 ]

[[slabs]]
min = [ -1000.0, -1000.0, -1000.0 ]
max = [ 1000.0, 0.0, 1000.0 ]
    [slabs.material]
    type = "diffuse"
    diffuse = [ 0.5, 0.5, 0.5 ]

